### ISSUE TITLE
Git tags

### ISSUE THREAD

**Issue by masutaka** [shunwen/fluent-plugin-rename-key#15]
@shunwen 

Could you push git tags `v0.3.3`, `v0.3.4` and `v0.4.0` to GitHub? I want to compare each versions.

* https://github.com/shunwen/fluent-plugin-rename-key/releases
* https://rubygems.org/gems/fluent-plugin-rename-key/versions

Thanks for your great gem!

**Comment by shunwen** [comment]
@masutaka Sure, I will do it this weekend.

**Comment by shunwen** [comment]
@masutaka Tags are ready.

**Comment by masutaka** [comment]
@shunwen Thanks a lot!
