### ISSUE TITLE
How to delete special characters?

### ISSUE THREAD

**Issue by jeffsink** [shunwen/fluent-plugin-rename-key#17]
If I want to delete special characters, what is the easiest way to do it using this tool?

for example, I want to replicate the sed functionality of:

s/[^0-1a-zA-Z_]//g

that is, all characters that are not (alphanumeric and underscore) are removed //

I thought of a few ways, but the trouble is that the good stuff, the content we want to keep, would appear in an unknown number of placeholders ${md[1]} , ${md[2]}, ${md[3]}. ...  I cannot see how to join these.

In Ruby, this would be like:
"myKey".gsub(/[^0-1a-zA-Z_]/, "")

Any help is appreciated!

Thanks!

Jeff

**Comment by shunwen** [comment]
@jeffsink Hi, sorry for the late response. You can try `replace_rule` see if that works. Remove special chars in the first rule, and use other rules to rename with the placeholders.

````
replace_rule1 /[^0-1a-zA-Z_]/ ''
````

Here's what we have in README.

````
# <num> is an integer for ordering rules, rules are checked in ascending order. Only the first match is applied.
# <key_regexp> is the regular expression to match keys, ' '(whitespace) is not allowed, use '\s' instead.
# <new_key> is the pattern to replace the matches with, MatchData placeholder '${md[1]}' and whitespace are allowed. 
#           This field is optional, if missing the matches will be replaced with ''(empty string).
replace_rule<num> <key_regexp> <new_key>
````

**Comment by xxwolfsrainxx** [comment]
@shunwen This does not work. I've tried it myself. the replace rule seems to do nothing.

**Comment by xxwolfsrainxx** [comment]
After messing around the correct answer is:
`<filter>
    @type rename_key
    replace_rule1 ([^0-1a-zA-Z_])
</filter>`
Put that in your config

**Comment by xxwolfsrainxx** [comment]
This should be closed as the intended functionality is provided.

**Comment by shunwen** [comment]
@xxwolfsrainxx Thanks.
