### ISSUE TITLE
Any patterns available to change all uppercase letters in field names to lowercase?

### ISSUE THREAD

**Issue by rafaelmagu** [shunwen/fluent-plugin-rename-key#19]
I've been trying to use this plugin to rename all fields from uppercase to lowercase (systemd input plugin in Fluent Bit exports everything in uppercase) and it messes with some keys.

**Comment by rafaelmagu** [comment]
Pattern I attempted:

```
<filter **.**>
  @type rename_key
  rename_rule1 ^(.*) \L${md[1]}
</filter>
```

**Comment by shunwen** [comment]
Hi @rafaelmagu , sorry for the late response. I didn't implement any pattern to transform the matches but only to rearrange their position in the key. Nice profile picture by the way.

**Comment by rafaelmagu** [comment]
Thanks for the response, and the compliment!

**Comment by gabe-sorensen** [comment]
@rafaelmagu I'm trying to accomplish the same thing. Did you ever find a way to lowercase all the keys? I've looked at a bunch of different plugins but haven't found a way yet.

**Comment by rafaelmagu** [comment]
Hey @gabe-sorensen, I ended up switching to Fluentd. Its SystemD plugin has an option to convert all to lowercase:

```
# Systemd input
<source>
  @type systemd
  tag systemd
  path /var/log/journal
  read_from_head true

  <storage>
    @type local
    path /var/run/td-agent/systemd
  </storage>

  <entry>
    fields_strip_underscores true
    fields_lowercase true
  </entry>
  @label @PROCESS
</source>
```

**Comment by gabe-sorensen** [comment]
Thanks @rafaelmagu, as another option, I ended up using the Lua plugin on the fluent-bit side with the following script:
`function lowercase_keys(tag, timestamp, record)
    new_record = {}
    for key,value in pairs(record) do
        new_record[string.lower(key)] = value
    end
    return 1, timestamp, new_record
end`

**Comment by Blobonat** [comment]
I created a simple filter plugin for Fluentd which changes all field key names of a record to lowercase: https://github.com/Blobonat/fluentd-key-lowercase-plugin
