### ISSUE TITLE
Not able to find plugin

### ISSUE THREAD

**Issue by sk3749614** [shunwen/fluent-plugin-rename-key#9]
I installed the plugin. But when I try to use it, fluentd won't start up. Any ideas? I tried both gem install and td-agent-gem install

sudo td-agent-gem install fluent-plugin-rename-key
Successfully installed fluent-plugin-rename-key-0.2.0
Parsing documentation for fluent-plugin-rename-key-0.2.0
Done installing documentation for fluent-plugin-rename-key after 0 seconds
1 gem installed

Done installing documentation for msgpack, yajl-ruby, cool.io, sigdump, serverengine, http_parser.rb, thread_safe, tzinfo, tzinfo-data, strptime, fluentd, fluent-plugin-rename-key after 9 seconds
12 gems installed

When starting up td-agent, I get the following error

2016-07-14 17:47:42 +0000 [info]: adding filter pattern="_._*" type="rename_key"
2016-07-14 17:47:42 +0000 [error]: config error file="/etc/td-agent/td-agent.conf" error="Unknown filter plugin 'rename_key'. Run 'gem search -rd fluent-plugin' to find plugins"

It is a problem if I use it as a filter but works if I use it as a match.  I need to combine it with another match. Any ideas on how to do this?

<match *.**>
  type rename_key
  #remove_tag_prefix input.test
  #append_tag renamed
  rename_rule1 . _
</match>

The following doesn't work

<filter *.**>
  type rename_key
  #remove_tag_prefix input.test
  #append_tag renamed
  rename_rule1 . _
</filter>

**Comment by shunwen** [comment]
@sk3749614 Sorry for the late response. At the time I wrote this plugin it only works when using as a match, you need to **chain-match** to process the log (which is a pain in the neck).

I will look into it some time this month. Do you have any reference to fluentd doc/manual for the feature/syntax you are trying to use?

**Comment by cosmo0920** [comment]
> 2016-07-14 17:47:42 +0000 [info]: adding filter pattern=".*" type="rename_key"
2016-07-14 17:47:42 +0000 [error]: config error file="/etc/td-agent/td-agent.conf" error="Unknown filter plugin 'rename_key'. Run 'gem search -rd fluent-plugin' to find plugins"

It seems that Fluentd complains "Filter version of rename_key plugin not found.".
Creating filter version of rename_key will solve this issue.

**Comment by shunwen** [comment]
Merged PR#10.

**Comment by shunwen** [comment]
@sk3749614 The PR from @cosmo0920 is merged and released as version 0.3.2 (Because I messed up some build so needed to bump up more than one versions). Please try and see if it fixes your problem.

**Comment by cosmo0920** [comment]
Hmm, I think that `~> v0.14` constraint is too tight requirement because v0.14 is not announced as stable version for now.
Could you specify Fluentd dependency as follows in gemspec right now?

```ruby
gem.add_runtime_dependency "fluentd", [">= 0.12.0", "< 2"]
```

**Comment by shunwen** [comment]
@cosmo0920 Yes, thanks. Fixed in 0.3.3, yanked 0.3.2 from rubygems.
